export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const metric = searchParams.get("metric") || "rewards"
  const limit = Number.parseInt(searchParams.get("limit") || "10", 10)

  // Mock leaderboard data
  const leaderboard = [
    {
      id: "1",
      name: "Elite-pNode-001",
      status: "active" as const,
      uptime: 99.99,
      latency: 28,
      validations: 28934,
      rewards: 12456.78,
      location: "Singapore",
      lastUpdated: Date.now(),
      performance: 99,
      stake: 45000,
      riskScore: 5,
    },
    {
      id: "2",
      name: "Premium-pNode-Tokyo",
      status: "active" as const,
      uptime: 99.98,
      latency: 32,
      validations: 26500,
      rewards: 11234.56,
      location: "Tokyo, Japan",
      lastUpdated: Date.now(),
      performance: 98,
      stake: 42000,
      riskScore: 8,
    },
    {
      id: "3",
      name: "Advanced-NYC-001",
      status: "active" as const,
      uptime: 99.95,
      latency: 45,
      validations: 24123,
      rewards: 10567.89,
      location: "New York, USA",
      lastUpdated: Date.now(),
      performance: 97,
      stake: 40000,
      riskScore: 12,
    },
    {
      id: "4",
      name: "Standard-London-042",
      status: "active" as const,
      uptime: 99.92,
      latency: 52,
      validations: 21456,
      rewards: 9234.12,
      location: "London, UK",
      lastUpdated: Date.now(),
      performance: 96,
      stake: 35000,
      riskScore: 15,
    },
    {
      id: "5",
      name: "Core-Sydney-018",
      status: "active" as const,
      uptime: 99.88,
      latency: 38,
      validations: 19876,
      rewards: 8456.23,
      location: "Sydney, Australia",
      lastUpdated: Date.now(),
      performance: 95,
      stake: 33000,
      riskScore: 18,
    },
    {
      id: "6",
      name: "Hub-Frankfurt-033",
      status: "active" as const,
      uptime: 99.85,
      latency: 48,
      validations: 18234,
      rewards: 7834.56,
      location: "Frankfurt, Germany",
      lastUpdated: Date.now(),
      performance: 94,
      stake: 30000,
      riskScore: 22,
    },
  ]

  return Response.json(leaderboard.slice(0, limit))
}
